# Generated by Django 4.0.3 on 2022-03-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_books_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='price',
            new_name='amount',
        ),
    ]
